/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { RolePermission } from '../model/rolePermission';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class RolePermissionControllerService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * associateRolePermission
     *
     * @param idPermission idPermission
     * @param idRole idRole
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public associateRolePermissionUsingPOST(idPermission: number, idRole: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public associateRolePermissionUsingPOST(idPermission: number, idRole: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public associateRolePermissionUsingPOST(idPermission: number, idRole: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public associateRolePermissionUsingPOST(idPermission: number, idRole: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPermission === null || idPermission === undefined) {
            throw new Error('Required parameter idPermission was null or undefined when calling associateRolePermissionUsingPOST.');
        }

        if (idRole === null || idRole === undefined) {
            throw new Error('Required parameter idRole was null or undefined when calling associateRolePermissionUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<any>(`${this.basePath}/v1/roles-permissions/roles/${encodeURIComponent(String(idRole))}/permissions/${encodeURIComponent(String(idPermission))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * disassociateRolePermission
     *
     * @param idPermission idPermission
     * @param idRole idRole
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public disassociateRolePermissionUsingDELETE(idPermission: number, idRole: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public disassociateRolePermissionUsingDELETE(idPermission: number, idRole: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public disassociateRolePermissionUsingDELETE(idPermission: number, idRole: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public disassociateRolePermissionUsingDELETE(idPermission: number, idRole: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idPermission === null || idPermission === undefined) {
            throw new Error('Required parameter idPermission was null or undefined when calling disassociateRolePermissionUsingDELETE.');
        }

        if (idRole === null || idRole === undefined) {
            throw new Error('Required parameter idRole was null or undefined when calling disassociateRolePermissionUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/v1/roles-permissions/roles/${encodeURIComponent(String(idRole))}/permissions/${encodeURIComponent(String(idPermission))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAll
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllUsingGET2(observe?: 'body', reportProgress?: boolean): Observable<Array<RolePermission>>;
    public getAllUsingGET2(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<RolePermission>>>;
    public getAllUsingGET2(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<RolePermission>>>;
    public getAllUsingGET2(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<RolePermission>>(`${this.basePath}/v1/roles-permissions`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getPermissionsByRole
     *
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPermissionsByRoleUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<Array<RolePermission>>;
    public getPermissionsByRoleUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<RolePermission>>>;
    public getPermissionsByRoleUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<RolePermission>>>;
    public getPermissionsByRoleUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getPermissionsByRoleUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<RolePermission>>(`${this.basePath}/v1/roles-permissions/roles/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
